# Метаданные проекта
project_name: lv

# Переменные окружения при сборке
env:
  - CGO_ENABLED=0  # статическая сборка

before:
  hooks:
    - go mod tidy  # очистка зависимостей перед сборкой

# Настройка сборки
builds:
  - main: .  # main.go в корне
    binary: lv
    ldflags:
      - -s -w  # уменьшаем размер
      - -X main.version={{.Version}}
    flags:
      - -trimpath  # воспроизводимая сборка
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64  # пока не поддерживаем Windows ARM64

# Настройка архивов
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    # Включаем только бинарник и LICENSE/README
    files:
      - LICENSE
      - README.md
    wrap_in_directory: true

# Проверочные суммы
checksum:
  name_template: "checksums.txt"
  algorithm: sha256

# Changelog
changelog:
  sort: asc
  groups:
    - title: "New Features"
      regexp: "^.*feat[(:].*$"
    - title: "Bug Fixes"
      regexp: "^.*fix[(:].*$"
  filters:
    exclude:
      - "^docs:"
      - "^test:"